FROM python:3.12-slim

# Устанавливаем рабочую директорию в контейнере
WORKDIR /service

# Копируем файл requirements.txt в рабочую директорию
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем содержимое директории server в рабочую директорию
COPY server/ ./server/

# Указываем команду для запуска приложения
CMD ["uvicorn", "server.shop_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
